spring.datasource.url=jdbc:postgresql://dpg-d8d1bpjbc2fs73fhdh80-a:5432/tpv_6afi
spring.datasource.username=tpv_6afi_user
spring.datasource.password=TU_PASSWORD

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080